import React from "react";
import {
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { router } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Feather } from "@expo/vector-icons";
import { useColors } from "@/hooks/useColors";

const LAST_UPDATED = "June 30, 2026";
const CONTACT_EMAIL = "studiosvirelle@gmail.com";

export default function TermsScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      {/* Header */}
      <View
        style={[
          styles.header,
          {
            paddingTop: insets.top + (Platform.OS === "web" ? 67 : 16),
            borderBottomColor: colors.border,
          },
        ]}
      >
        <TouchableOpacity
          onPress={() => router.back()}
          hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
        >
          <Feather name="arrow-left" size={22} color={colors.foreground} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.foreground }]}>
          Terms of Service
        </Text>
        <View style={{ width: 22 }} />
      </View>

      <ScrollView
        contentContainerStyle={[
          styles.content,
          { paddingBottom: insets.bottom + 40 },
        ]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={[styles.updated, { color: colors.mutedForeground }]}>
          Last Updated: {LAST_UPDATED}
        </Text>

        {/* Critical disclaimer banner */}
        <View style={[styles.criticalBox, { backgroundColor: "#3B1A00", borderColor: "#C8810040" }]}>
          <Feather name="alert-triangle" size={18} color="#F59E0B" />
          <Text style={styles.criticalText}>
            IMPORTANT: PeacemakerAI is a conflict resolution and entertainment platform. It is NOT a legal service, NOT a licensed counselling service, and NOT a substitute for professional legal, therapeutic, or law enforcement intervention. No ruling, observation, or recommendation made within this app constitutes legal advice, a court order, or professional opinion of any kind.
          </Text>
        </View>

        <Section title="1. Agreement to These Terms" colors={colors}>
          <Body colors={colors}>
            Welcome to PeacemakerAI, operated by Virelle, Inc. ("PeacemakerAI", "we", "us", or "our"). By downloading, accessing, or using this application and its services (the "App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, you must not use the App.{"\n\n"}
            These Terms apply to all users, including individuals who have created accounts and those who access the App as a guest or invitee (as a responding party to a summons).
          </Body>
        </Section>

        <Section title="2. What PeacemakerAI Is (and Is Not)" colors={colors}>
          <Body colors={colors}>
            PeacemakerAI is an AI-assisted conflict resolution platform designed for{" "}
            <Bold>entertainment purposes and everyday interpersonal dispute resolution</Bold>
            {" "}— such as relationship disagreements, friendship conflicts, and everyday misunderstandings between individuals who choose to participate voluntarily.{"\n\n"}
            The platform uses artificial intelligence to simulate a neutral judicial process. The "judges" within the App are fictional AI personas. They do not hold any legal qualifications, professional certifications, or official authority of any kind.{"\n\n"}
            PeacemakerAI is{" "}
            <Bold>not</Bold>
            {" "}a law firm, mediation service, arbitration service, counselling practice, social services agency, or any form of licensed professional service.
          </Body>
        </Section>

        <Section title="3. Not a Legal, Therapeutic, or Professional Service" colors={colors}>
          <Body colors={colors}>
            <Bold>No advice, ruling, observation, verdict, or recommendation generated by this App — whether by the AI judge or any other feature — constitutes legal advice, professional legal opinion, therapeutic advice, medical advice, or any other form of licensed professional advice.</Bold>
            {"\n\n"}
            Nothing produced by PeacemakerAI should be treated as such, relied upon in legal proceedings, submitted as evidence in any court, or used as the basis for any legal, financial, medical, or professional decision.{"\n\n"}
            If you need professional advice, you should consult a qualified and licensed lawyer, therapist, mediator, financial advisor, or other relevant professional in your jurisdiction.
          </Body>
        </Section>

        <Section title="4. Official Court Orders and Police Orders Take Absolute Precedence" colors={colors}>
          <WarningBox colors={colors}>
            No ruling, outcome, or recommendation made by PeacemakerAI supersedes, modifies, replaces, or overrides any official court order, police order, restraining order, custody order, protective order, or any other legally binding decision or instrument issued by a court, tribunal, law enforcement agency, or other official authority.
          </WarningBox>
          <Body colors={colors}>
            If you or any other party is subject to an existing legal order, that order must be followed at all times. PeacemakerAI cannot and does not alter the terms or effect of any such order. If there is any conflict between what this App suggests and what a legal order requires, the legal order governs absolutely.{"\n\n"}
            Using this App does not create any legal relationship, agreement, or obligation between parties that would have any standing before a court or other official body.
          </Body>
        </Section>

        <Section title="5. Cases Outside the Scope of This Platform" colors={colors}>
          <Body colors={colors}>
            PeacemakerAI is designed for everyday interpersonal and relationship disputes. The following matters are{" "}
            <Bold>outside the scope of this platform</Bold>
            {" "}and must be handled through your local judicial system, law enforcement, or qualified professionals:
          </Body>
          <BulletList colors={colors} items={[
            "Estate disputes, inheritance conflicts, and will execution — consult a solicitor or estate lawyer in your jurisdiction.",
            "Financial disputes involving debts, contracts, business agreements, or consumer rights — consult a financial advisor or civil lawyer.",
            "Criminal matters of any kind, including assault, theft, fraud, harassment, stalking, and domestic violence — report to local police or law enforcement.",
            "Child custody and access arrangements that are subject to existing court orders — follow the court order and consult a family lawyer.",
            "Employment disputes, workplace discrimination, or industrial relations matters — consult the relevant employment authority or a labour lawyer.",
            "Immigration, visa, or citizenship matters — consult a registered immigration lawyer.",
            "Any matter involving a currently active investigation by police or other authorities.",
          ]} />
          <Body colors={colors}>
            If you submit a case that falls into any of these categories, the App will decline to proceed and direct you to the appropriate professional resources.
          </Body>
        </Section>

        <Section title="6. Safety, Severity, and Referrals to Authorities" colors={colors}>
          <Body colors={colors}>
            The safety of our users is our first priority. PeacemakerAI includes an automated safety detection system. In cases involving any of the following, the App will{" "}
            <Bold>immediately halt all dispute resolution proceedings</Bold>
            {" "}and direct you to relevant emergency services and professional support instead:
          </Body>
          <BulletList colors={colors} items={[
            "Domestic violence or physical abuse — active or ongoing.",
            "Child abuse or neglect of any kind.",
            "Sexual assault or coercion.",
            "Active criminal behaviour or an immediately dangerous situation.",
            "Suicide or self-harm crisis.",
            "Threats involving weapons or kidnapping.",
          ]} />
          <Body colors={colors}>
            In these situations, PeacemakerAI will provide direct contact information for relevant emergency services, crisis hotlines, shelters, child protection services, and mental health resources.{"\n\n"}
            <Bold>We do not and will not attempt to resolve situations involving immediate physical danger, active crimes, or any matter that requires the immediate involvement of law enforcement or emergency services through our dispute resolution process.</Bold>
          </Body>
        </Section>

        <Section title="7. Participation and User Responsibilities" colors={colors}>
          <Body colors={colors}>
            By using PeacemakerAI, you agree that:
          </Body>
          <BulletList colors={colors} items={[
            "You are participating voluntarily. Neither party is compelled to use this App or to accept any outcome it produces.",
            "You will provide truthful, accurate information when filing a case or responding to one.",
            "You will not use the App to harass, threaten, or intimidate any other person.",
            "You will not submit false, fabricated, or deliberately misleading accounts of events.",
            "You are responsible for how you choose to act on any outcome, suggestion, or ruling produced by the App.",
            "You must be at least 10 years of age to use this App. Users under 18 are subject to age-appropriate terms and parental supervision is encouraged.",
            "You will not use this App in connection with any active legal proceedings without obtaining independent legal advice.",
          ]} />
        </Section>

        <Section title="8. AI-Generated Rulings and Content" colors={colors}>
          <Body colors={colors}>
            The AI judges within PeacemakerAI are fictional personas powered by large language model AI technology. Their rulings, questions, and observations are generated algorithmically and do not represent the views, opinions, or professional judgments of any human.{"\n\n"}
            AI rulings:
          </Body>
          <BulletList colors={colors} items={[
            "Are not legally binding in any jurisdiction.",
            "Should not be presented to any court, authority, employer, or third party as an official determination of any kind.",
            "May not always be accurate, balanced, or appropriate for every situation.",
            "Are generated based solely on the information provided by users and are inherently limited by the accuracy and completeness of that information.",
          ]} />
          <Body colors={colors}>
            The AI judges are programmed not to advise parties to marry, divorce, separate, use violence, or take any action that could cause harm. However, AI systems are imperfect. If you receive a response you believe is inappropriate, please contact us at {CONTACT_EMAIL}.
          </Body>
        </Section>

        <Section title="9. Subscriptions and In-App Purchases" colors={colors}>
          <Body colors={colors}>
            PeacemakerAI offers paid subscription plans and in-app purchases processed through Apple App Store and Google Play. All purchases are subject to the terms and conditions of the relevant app store platform.{"\n\n"}
            Subscriptions auto-renew unless cancelled at least 24 hours before the end of the current subscription period. Manage or cancel subscriptions through your device's App Store or Google Play account settings.{"\n\n"}
            We do not offer refunds except where required by applicable law or the policies of the relevant app store. All pricing is listed in Australian Dollars (AUD) or local equivalent as displayed in your region.
          </Body>
        </Section>

        <Section title="10. Privacy" colors={colors}>
          <Body colors={colors}>
            Your privacy is important to us. Case content, personal information, and conversation data submitted through PeacemakerAI is used solely for the purpose of providing the dispute resolution service.{"\n\n"}
            We do not sell your personal information to third parties. Case data may be used in aggregate and anonymised form to improve our services.{"\n\n"}
            By using PeacemakerAI, you acknowledge that the other party in your dispute may see the information you submit as part of your case filing, as this is necessary for the resolution process to function.
          </Body>
        </Section>

        <Section title="11. Limitation of Liability" colors={colors}>
          <Body colors={colors}>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PEACEMAKER AI, VIRELLE INC., ITS AFFILIATES, DIRECTORS, EMPLOYEES, AGENTS, AND LICENSORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE APP.{"\n\n"}
            THIS INCLUDES, WITHOUT LIMITATION, ANY DAMAGES ARISING FROM:{"\n"}
            — DECISIONS MADE IN RELIANCE ON ANY AI-GENERATED RULING OR CONTENT;{"\n"}
            — FAILURE TO REFER SERIOUS MATTERS TO APPROPRIATE AUTHORITIES;{"\n"}
            — ANY ACTION OR INACTION BY EITHER PARTY FOLLOWING USE OF THE APP;{"\n"}
            — LOSS OF DATA, RELATIONSHIP HARM, EMOTIONAL DISTRESS, OR FINANCIAL LOSS.{"\n\n"}
            THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE FROM HARMFUL CONTENT.{"\n\n"}
            OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING OUT OF THESE TERMS OR YOUR USE OF THE APP SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM, OR AUD $100, WHICHEVER IS LESS.
          </Body>
        </Section>

        <Section title="12. Indemnification" colors={colors}>
          <Body colors={colors}>
            You agree to defend, indemnify, and hold harmless PeacemakerAI, Virelle Inc., and its officers, directors, employees, and agents from and against any claims, damages, obligations, losses, liabilities, costs, or expenses (including legal fees) arising from:{"\n"}
            (a) your use of the App;{"\n"}
            (b) your violation of these Terms;{"\n"}
            (c) any information you submit to the App that is false, defamatory, or infringes on the rights of another person;{"\n"}
            (d) any harm caused to another party as a result of how you acted upon any outcome produced by the App.
          </Body>
        </Section>

        <Section title="13. Governing Law" colors={colors}>
          <Body colors={colors}>
            These Terms shall be governed by and construed in accordance with the laws of the State of Victoria, Australia, without regard to its conflict of law provisions. You agree to submit to the personal and exclusive jurisdiction of the courts located in Victoria, Australia for the resolution of any disputes arising under these Terms.{"\n\n"}
            If you are located outside of Australia, you acknowledge that your use of the App is subject to these governing law provisions, and that local laws in your jurisdiction may provide additional consumer protections that are not affected by this clause.
          </Body>
        </Section>

        <Section title="14. Changes to These Terms" colors={colors}>
          <Body colors={colors}>
            We reserve the right to modify these Terms at any time. If we make a material change, we will notify you through the App or by email at least 14 days before the change takes effect. Your continued use of the App after that date constitutes your acceptance of the updated Terms.{"\n\n"}
            We encourage you to review these Terms periodically.
          </Body>
        </Section>

        <Section title="15. Contact Us" colors={colors}>
          <Body colors={colors}>
            If you have questions about these Terms, believe you have received an inappropriate AI response, or wish to report a concern, please contact us at:{"\n\n"}
            {CONTACT_EMAIL}{"\n\n"}
            PeacemakerAI is a product of Virelle, Inc.
          </Body>
        </Section>

        <View style={[styles.footer, { borderTopColor: colors.border }]}>
          <Text style={[styles.footerText, { color: colors.mutedForeground }]}>
            By using PeacemakerAI you confirm you have read, understood, and agree to these Terms of Service.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

// ── Sub-components ────────────────────────────────────────────────────────────

function Section({
  title,
  colors,
  children,
}: {
  title: string;
  colors: ReturnType<typeof import("@/hooks/useColors").useColors>;
  children: React.ReactNode;
}) {
  return (
    <View style={styles.section}>
      <Text style={[styles.sectionTitle, { color: colors.primary }]}>{title}</Text>
      {children}
    </View>
  );
}

function Body({
  colors,
  children,
}: {
  colors: ReturnType<typeof import("@/hooks/useColors").useColors>;
  children: React.ReactNode;
}) {
  return <Text style={[styles.body, { color: colors.foreground }]}>{children}</Text>;
}

function Bold({ children }: { children: React.ReactNode }) {
  return <Text style={styles.bold}>{children}</Text>;
}

function WarningBox({
  colors,
  children,
}: {
  colors: ReturnType<typeof import("@/hooks/useColors").useColors>;
  children: React.ReactNode;
}) {
  return (
    <View style={[styles.warningBox, { backgroundColor: colors.card, borderColor: colors.primary + "55" }]}>
      <Feather name="shield" size={15} color={colors.primary} style={{ marginTop: 2 }} />
      <Text style={[styles.warningText, { color: colors.foreground }]}>{children}</Text>
    </View>
  );
}

function BulletList({
  colors,
  items,
}: {
  colors: ReturnType<typeof import("@/hooks/useColors").useColors>;
  items: string[];
}) {
  return (
    <View style={styles.bulletList}>
      {items.map((item, i) => (
        <View key={i} style={styles.bulletRow}>
          <View style={[styles.bullet, { backgroundColor: colors.primary }]} />
          <Text style={[styles.bulletText, { color: colors.foreground }]}>{item}</Text>
        </View>
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
  },
  headerTitle: { fontSize: 17, fontFamily: "Inter_600SemiBold" },
  content: { padding: 24, gap: 24 },
  updated: { fontSize: 12, fontFamily: "Inter_400Regular" },
  criticalBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
  },
  criticalText: {
    flex: 1,
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    color: "#F59E0B",
    lineHeight: 20,
  },
  section: { gap: 12 },
  sectionTitle: {
    fontSize: 15,
    fontFamily: "Inter_700Bold",
    lineHeight: 22,
  },
  body: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    lineHeight: 22,
  },
  bold: {
    fontFamily: "Inter_600SemiBold",
  },
  warningBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderRadius: 12,
    borderWidth: 1,
    padding: 14,
  },
  warningText: {
    flex: 1,
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    lineHeight: 21,
  },
  bulletList: { gap: 10, paddingLeft: 4 },
  bulletRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  bullet: { width: 5, height: 5, borderRadius: 3, marginTop: 8, flexShrink: 0 },
  bulletText: {
    flex: 1,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    lineHeight: 21,
  },
  footer: {
    borderTopWidth: 1,
    paddingTop: 24,
    marginTop: 8,
  },
  footerText: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 18,
  },
});
