export const DANGER_KEYWORDS = [
  "hit me",
  "hitting me",
  "beats me",
  "beat me",
  "hurts me",
  "punch",
  "choke",
  "strangle",
  "kill",
  "murder",
  "abuse",
  "abusing",
  "threaten",
  "threatened",
  "weapon",
  "knife",
  "gun",
  "suicide",
  "kill myself",
  "harm myself",
  "self harm",
  "end my life",
  "rape",
  "assault",
  "molest",
  "touch me",
  "forced me",
  "trapped",
  "can't leave",
  "wont let me leave",
  "won't let me leave",
  "locked",
  "hostage",
  "blackmail",
  "stalking",
  "stalker",
  "followed me",
  "scared for my life",
  "afraid of my",
];

export function detectDanger(text: string): boolean {
  const lower = text.toLowerCase();
  return DANGER_KEYWORDS.some((keyword) => lower.includes(keyword));
}
